### ISSUE TITLE
Admin Tasks

### ISSUE THREAD

**Issue by ThePlugZA** [ThePlugZA/CineTech#26]
# Link all input fields
Build up a request body based on the input fields.  
Call `deleteUser, AddMovie, AddShow, Edit,`.

**Comment by YourfavCompSciGirlie** [comment]
Request bodies done, Completed Edit Movies/Series functions and debugged everything to work!

**Comment by ThePlugZA** [comment]
Add drop down for movie/series option

**Comment by YourfavCompSciGirlie** [comment]
Added
